name: flutter_notebook_chapter_40
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  gap:  ^3.0.1
  hugeicons: ^0.0.7
  genq: ^0.3.0
  signals: ^5.5.0
  cupertino_icons:
  percent_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
